language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
deploy:
  provider: firebase
  skip_cleanup: true
  firebase_token: $FIREBASE_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: ./build
